### ISSUE TITLE
MVC Component: Car Details (Popup)

### ISSUE THREAD

**Issue by PavelKundenko** [so2niko/Dp-193_proj1#27]
**SHOULD BE UPDATED**
- Add checkboxes: 
  - Color
  - Transmission
![image](https://user-images.githubusercontent.com/47292994/95658593-4805cd00-0b24-11eb-8e76-30c8ae38dfdd.png)

**Comment by iklopov** [comment]
https://drive.google.com/file/d/14msdlBx47z641r-Khp2GtBAPcsqtEPNY/view?usp=sharing

**Comment by Anastasiia0999** [comment]
- Transmission
Two possible options: automatic, manual ( check database)

**Comment by iklopov** [comment]
https://drive.google.com/file/d/1R7YFRbMpSR6WTGmQ6zdsaXOptsGahm2K/view?usp=sharing
