### ISSUE TITLE
Design and MVC component: Confirm Order

### ISSUE THREAD

**Issue by PavelKundenko** [so2niko/Dp-193_proj1#29]
Should include detailed info about selected car
Form should include: 
- Name Surname
- Phone
- Email

**Comment by MarinaPasternak** [comment]
![FormAccept](https://user-images.githubusercontent.com/31963187/95729937-418f6680-0c86-11eb-84ae-8e0255777fa1.jpg)

**Comment by Anastasiia0999** [comment]
Data should be translated
