### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by so2niko** [so2niko/Dp-193_proj1#4]
#### Header

- Logo
- Title
- Slider
- Search
- Navigation
  - Contacts
  - Main page

#### Main

- Auto cards
- Filter
- Load more button (...)

#### Footer

- made by ...
- Address

#### Modal

- Call to me button vs modal form (input phone number)

**Comment by Winchestery** [comment]
link to layouts in figma
should you have any remarks or questions, feel free to edit 
[https://www.figma.com/file/airY16nSvCCG6LdWWbIlDg/Untitled?node-id=1%3A8](url)

**Comment by so2niko** [comment]
4 cards in row
